name: 'compile peerconnection so'

on:
  push

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cm
          git pull
          compile_peerconnection.sh
